sub asn_blocklist {

# AUTOGENERATED ASN BLOCKLIST
# DO NOT EDIT MANUALLY


    if (req.http.X-ASN-ID == "51896") {
        set req.http.X-Match = "asn-as51896";
        return (synth(403, "Blocked ASN: 672 (AS51896)"));
    }

    if (req.http.X-ASN-ID == "207990") {
        set req.http.X-Match = "asn-as207990";
        return (synth(403, "Blocked ASN: 118 (AS207990)"));
    }

    if (req.http.X-ASN-ID == "13238") {
        set req.http.X-Match = "asn-as13238";
        return (synth(403, "Blocked ASN: 105 (AS13238)"));
    }

    if (req.http.X-ASN-ID == "209366") {
        set req.http.X-Match = "asn-as209366";
        return (synth(403, "Blocked ASN: 76 (AS209366)"));
    }

    if (req.http.X-ASN-ID == "20473") {
        set req.http.X-Match = "asn-as20473";
        return (synth(403, "Blocked ASN: 41 (AS20473)"));
    }

    if (req.http.X-ASN-ID == "64079") {
        set req.http.X-Match = "asn-as64079";
        return (synth(403, "Blocked ASN: 38 (AS64079)"));
    }

    if (req.http.X-ASN-ID == "131366") {
        set req.http.X-Match = "asn-as131366";
        return (synth(403, "Blocked ASN: 31 (AS131366)"));
    }

    if (req.http.X-ASN-ID == "401332") {
        set req.http.X-Match = "asn-as401332";
        return (synth(403, "Blocked ASN: 31 (AS401332)"));
    }

    if (req.http.X-ASN-ID == "44788") {
        set req.http.X-Match = "asn-as44788";
        return (synth(403, "Blocked ASN: 21 (AS44788)"));
    }

    if (req.http.X-ASN-ID == "8342") {
        set req.http.X-Match = "asn-as8342";
        return (synth(403, "Blocked ASN: 20 (AS8342)"));
    }

    if (req.http.X-ASN-ID == "51167") {
        set req.http.X-Match = "asn-as51167";
        return (synth(403, "Blocked ASN: 14 (AS51167)"));
    }

    if (req.http.X-ASN-ID == "37963") {
        set req.http.X-Match = "asn-as37963";
        return (synth(403, "Blocked ASN: 13 (AS37963)"));
    }

    if (req.http.X-ASN-ID == "151858") {
        set req.http.X-Match = "asn-as151858";
        return (synth(403, "Blocked ASN: 13 (AS151858)"));
    }

    if (req.http.X-ASN-ID == "54183") {
        set req.http.X-Match = "asn-as54183";
        return (synth(403, "Blocked ASN: 11 (AS54183)"));
    }

    if (req.http.X-ASN-ID == "43754") {
        set req.http.X-Match = "asn-as43754";
        return (synth(403, "Blocked ASN: 11 (AS43754)"));
    }

    if (req.http.X-ASN-ID == "263744") {
        set req.http.X-Match = "asn-as263744";
        return (synth(403, "Blocked ASN: 10 (AS263744)"));
    }

    if (req.http.X-ASN-ID == "53107") {
        set req.http.X-Match = "asn-as53107";
        return (synth(403, "Blocked ASN: 9 (AS53107)"));
    }

    if (req.http.X-ASN-ID == "135918") {
        set req.http.X-Match = "asn-as135918";
        return (synth(403, "Blocked ASN: 8 (AS135918)"));
    }

    if (req.http.X-ASN-ID == "42422") {
        set req.http.X-Match = "asn-as42422";
        return (synth(403, "Blocked ASN: 8 (AS42422)"));
    }

    if (req.http.X-ASN-ID == "41041") {
        set req.http.X-Match = "asn-as41041";
        return (synth(403, "Blocked ASN: 6 (AS41041)"));
    }

    if (req.http.X-ASN-ID == "211590") {
        set req.http.X-Match = "asn-as211590";
        return (synth(403, "Blocked ASN: 6 (AS211590)"));
    }

    if (req.http.X-ASN-ID == "48715") {
        set req.http.X-Match = "asn-as48715";
        return (synth(403, "Blocked ASN: 6 (AS48715)"));
    }

    if (req.http.X-ASN-ID == "3214") {
        set req.http.X-Match = "asn-as3214";
        return (synth(403, "Blocked ASN: 6 (AS3214)"));
    }

    if (req.http.X-ASN-ID == "200000") {
        set req.http.X-Match = "asn-as200000";
        return (synth(403, "Blocked ASN: 6 (AS200000)"));
    }

    if (req.http.X-ASN-ID == "397715") {
        set req.http.X-Match = "asn-as397715";
        return (synth(403, "Blocked ASN: 6 (AS397715)"));
    }

    if (req.http.X-ASN-ID == "64458") {
        set req.http.X-Match = "asn-as64458";
        return (synth(403, "Blocked ASN: 5 (AS64458)"));
    }

    if (req.http.X-ASN-ID == "40021") {
        set req.http.X-Match = "asn-as40021";
        return (synth(403, "Blocked ASN: 5 (AS40021)"));
    }

    if (req.http.X-ASN-ID == "199404") {
        set req.http.X-Match = "asn-as199404";
        return (synth(403, "Blocked ASN: 5 (AS199404)"));
    }

    if (req.http.X-ASN-ID == "136727") {
        set req.http.X-Match = "asn-as136727";
        return (synth(403, "Blocked ASN: 5 (AS136727)"));
    }

    if (req.http.X-ASN-ID == "212219") {
        set req.http.X-Match = "asn-as212219";
        return (synth(403, "Blocked ASN: 5 (AS212219)"));
    }

    if (req.http.X-ASN-ID == "212607") {
        set req.http.X-Match = "asn-as212607";
        return (synth(403, "Blocked ASN: 5 (AS212607)"));
    }

    if (req.http.X-ASN-ID == "4837") {
        set req.http.X-Match = "asn-as4837";
        return (synth(403, "Blocked ASN: 4 (AS4837)"));
    }

    if (req.http.X-ASN-ID == "135917") {
        set req.http.X-Match = "asn-as135917";
        return (synth(403, "Blocked ASN: 4 (AS135917)"));
    }

    if (req.http.X-ASN-ID == "135822") {
        set req.http.X-Match = "asn-as135822";
        return (synth(403, "Blocked ASN: 4 (AS135822)"));
    }

    if (req.http.X-ASN-ID == "151863") {
        set req.http.X-Match = "asn-as151863";
        return (synth(403, "Blocked ASN: 4 (AS151863)"));
    }

    if (req.http.X-ASN-ID == "135967") {
        set req.http.X-Match = "asn-as135967";
        return (synth(403, "Blocked ASN: 4 (AS135967)"));
    }

    if (req.http.X-ASN-ID == "47330") {
        set req.http.X-Match = "asn-as47330";
        return (synth(403, "Blocked ASN: 4 (AS47330)"));
    }

    if (req.http.X-ASN-ID == "134760") {
        set req.http.X-Match = "asn-as134760";
        return (synth(403, "Blocked ASN: 4 (AS134760)"));
    }

    if (req.http.X-ASN-ID == "12389") {
        set req.http.X-Match = "asn-as12389";
        return (synth(403, "Blocked ASN: 4 (AS12389)"));
    }

    if (req.http.X-ASN-ID == "19318") {
        set req.http.X-Match = "asn-as19318";
        return (synth(403, "Blocked ASN: 4 (AS19318)"));
    }

    if (req.http.X-ASN-ID == "135951") {
        set req.http.X-Match = "asn-as135951";
        return (synth(403, "Blocked ASN: 4 (AS135951)"));
    }

    if (req.http.X-ASN-ID == "19750") {
        set req.http.X-Match = "asn-as19750";
        return (synth(403, "Blocked ASN: 4 (AS19750)"));
    }

    if (req.http.X-ASN-ID == "131353") {
        set req.http.X-Match = "asn-as131353";
        return (synth(403, "Blocked ASN: 4 (AS131353)"));
    }

    if (req.http.X-ASN-ID == "45758") {
        set req.http.X-Match = "asn-as45758";
        return (synth(403, "Blocked ASN: 4 (AS45758)"));
    }

    if (req.http.X-ASN-ID == "208161") {
        set req.http.X-Match = "asn-as208161";
        return (synth(403, "Blocked ASN: 4 (AS208161)"));
    }

    if (req.http.X-ASN-ID == "45538") {
        set req.http.X-Match = "asn-as45538";
        return (synth(403, "Blocked ASN: 4 (AS45538)"));
    }

    if (req.http.X-ASN-ID == "46015") {
        set req.http.X-Match = "asn-as46015";
        return (synth(403, "Blocked ASN: 4 (AS46015)"));
    }

    if (req.http.X-ASN-ID == "56478") {
        set req.http.X-Match = "asn-as56478";
        return (synth(403, "Blocked ASN: 4 (AS56478)"));
    }

    if (req.http.X-ASN-ID == "30083") {
        set req.http.X-Match = "asn-as30083";
        return (synth(403, "Blocked ASN: 4 (AS30083)"));
    }

    if (req.http.X-ASN-ID == "132817") {
        set req.http.X-Match = "asn-as132817";
        return (synth(403, "Blocked ASN: 3 (AS132817)"));
    }

    if (req.http.X-ASN-ID == "4134") {
        set req.http.X-Match = "asn-as4134";
        return (synth(403, "Blocked ASN: 3 (AS4134)"));
    }

    if (req.http.X-ASN-ID == "3209") {
        set req.http.X-Match = "asn-as3209";
        return (synth(403, "Blocked ASN: 3 (AS3209)"));
    }

    if (req.http.X-ASN-ID == "3215") {
        set req.http.X-Match = "asn-as3215";
        return (synth(403, "Blocked ASN: 3 (AS3215)"));
    }

    if (req.http.X-ASN-ID == "212667") {
        set req.http.X-Match = "asn-as212667";
        return (synth(403, "Blocked ASN: 3 (AS212667)"));
    }

    if (req.http.X-ASN-ID == "214940") {
        set req.http.X-Match = "asn-as214940";
        return (synth(403, "Blocked ASN: 3 (AS214940)"));
    }

    if (req.http.X-ASN-ID == "134450") {
        set req.http.X-Match = "asn-as134450";
        return (synth(403, "Blocked ASN: 3 (AS134450)"));
    }

    if (req.http.X-ASN-ID == "137") {
        set req.http.X-Match = "asn-as137";
        return (synth(403, "Blocked ASN: 3 (AS137)"));
    }

    if (req.http.X-ASN-ID == "52238") {
        set req.http.X-Match = "asn-as52238";
        return (synth(403, "Blocked ASN: 3 (AS52238)"));
    }


}
